// Generated by CoffeeScript 1.4.0
(function() {
  var getWordCount, simpleTokenizer;

  window.initiated = false;

  getWordCount = function(e, t, tokenizer) {
    var msg, text, words,
      _this = this;
    if (tokenizer == null) {
      tokenizer = simpleTokenizer;
    }
    text = e.selectionText;
    words = tokenizer(text);
    if (text.length === 0) {
      msg = "No words selected";
    } else {
      msg = "" + words + " word" + (words > 1 ? 's' : '') + " selected";
    }
    if (window.initiated === !true) {
      chrome.tabs.executeScript(t.id, {
        file: "dialog.js"
      }, function(e) {
        window.initiated = true;
        chrome.tabs.sendMessage(t.id, {
          message: msg
        });
      });
    } else {
      chrome.tabs.sendMessage(t.id, {
        message: msg
      });
      return;
    }
  };

  simpleTokenizer = function(text) {
    return text.split(" ").length;
  };

  chrome.contextMenus.create({
    "title": "Word Count",
    "contexts": ["selection"],
    "onclick": getWordCount
  });

}).call(this);
