// Generated by CoffeeScript 1.4.0
(function() {
  var getWordCount, regexTokenizer, simpleTokenizer;

  simpleTokenizer = function(text) {
    return text.split(" ").length;
  };

  regexTokenizer = function(text) {
    var re;
    re = /[\w\.]+?([\.\']\w+?)?([\s\.',\):\]]+|$)/gi;
    return text.match(re).length;
  };

  getWordCount = function(e, t, tokenizer) {
    var responses,
      _this = this;
    if (tokenizer == null) {
      tokenizer = regexTokenizer;
    }
    responses = 0;
    chrome.tabs.executeScript(t.id, {
      code: 'chrome.extension.sendMessage({ loaded: document.getElementById(\'word-count-porganized\')!==null });'
    });
    chrome.extension.onMessage.addListener(function(req, sender, sendResponse) {
      var msg, text, words;
      responses += 1;
      text = e.selectionText;
      words = tokenizer(text);
      msg = "" + (text.length === 0 ? 'No' : words) + " word" + (words !== 1 ? 's' : '') + " selected";
      if (responses !== 1) {
        return;
      }
      if (req.loaded === false) {
        chrome.tabs.executeScript(t.id, {
          file: "dialog.js"
        }, function() {
          return chrome.tabs.sendMessage(t.id, {
            message: msg
          });
        });
      } else {
        chrome.tabs.sendMessage(t.id, {
          message: msg
        });
      }
    });
  };

  chrome.contextMenus.create({
    "title": "Count words",
    "contexts": ["selection"],
    "onclick": getWordCount
  });

}).call(this);
