// Generated by CoffeeScript 1.4.0
(function() {
  var getWordCount, simpleTokenizer;

  getWordCount = function(e, t, tokenizer) {
    var text, words;
    if (tokenizer == null) {
      tokenizer = simpleTokenizer;
    }
    text = e.selectionText;
    words = tokenizer(text);
    if (text.length === 0) {
      return alert("No words selected");
    } else {
      return alert("" + words + " word" + (words > 1 ? 's' : '') + " selected");
    }
  };

  simpleTokenizer = function(text) {
    return text.split(" ").length;
  };

  chrome.contextMenus.create({
    "title": "Word Count",
    "contexts": ["selection"],
    "onclick": getWordCount
  });

  /*
  <div style="
      width: 200px;
      position: fixed;
      z-index: 10000;
      background: rgba(10,10,10,0.6);
      left: 50%;
      top: 50%;
      text-align: center;
      padding: 10px;
      border-radius: 10px;
      color: white;
      font-family: sans-serif;
  ">123 Words Selected</div>
  */


}).call(this);
