// Generated by CoffeeScript 1.4.0

/*
Non-Modal Dialog

This is a simple non-modal dialog. It is injected as a content script and
listens for sendMessage from elsewhere in the script.
*/


(function() {
  var dialog, mark,
    _this = this;

  dialog = function(text) {
    var div, x,
      _this = this;
    div = document.createElement('div');
    div.style.width = "200px";
    div.style.margin = "-50px -105px 0 -105px";
    div.style.position = "fixed";
    div.style.zIndex = 10000;
    div.style.background = "rgba(10,10,10,0.6)";
    div.style.left = "50%";
    div.style.top = "50%";
    div.style.textAlign = "center";
    div.style.padding = "30px 20px";
    div.style.borderRadius = "10px";
    div.style.color = "white";
    div.style.fontFamily = "sans-serif";
    div.style.fontSize = "13pt";
    div.style.textShadow = "0 1px 0 rgba(0, 0, 0, 0.9)";
    div.innerText = text;
    document.body.appendChild(div);
    x = document.createElement('div');
    x.innerText = 'close';
    x.style.position = "absolute";
    x.style.right = "10px";
    x.style.fontSize = "10pt";
    x.style.top = "10px";
    x.style.cursor = "pointer";
    div.appendChild(x);
    return x.onclick = function() {
      return x.parentNode.parentNode.removeChild(x.parentNode);
    };
  };

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    return dialog(request.message);
  });

  if (document.getElementById("word-count-porganized") === null) {
    mark = document.createElement("div");
    mark.id = "word-count-porganized";
    document.body.appendChild(mark);
  }

}).call(this);
