// Generated by CoffeeScript 1.4.0
(function() {
  var passages, test, tokenizers;

  tokenizers = require('../src/tokenizers.js');

  passages = [
    {
      text: 'This is a test.',
      count: 4
    }, {
      text: 'Trying to count multiple      spaces.',
      count: 5
    }, {
      text: 'What about unfinished sentences',
      count: 4
    }, {
      text: "Dr.Robert doesn't believe punctuation in words works.",
      count: 7
    }
  ];

  test = function(tokenizer) {
    var counted, error_margin, errors, passage, _i, _len;
    errors = 0;
    error_margin = 0;
    for (_i = 0, _len = passages.length; _i < _len; _i++) {
      passage = passages[_i];
      counted = tokenizer(passage.text);
      console.log("Returned " + counted + " \tActual " + passage.count);
      errors += counted === passage.count ? 0 : 1;
      error_margin += Math.abs(counted - passage.count);
    }
    return console.log("Total Errors: " + errors + " (error margin of " + error_margin + ")");
  };

  console.log("Testing simpleTokenizer");

  test(tokenizers.simpleTokenizer);

  console.log("Testing regexTokenizer");

  test(tokenizers.regexTokenizer);

}).call(this);
